import tkinter
import csv
root = tkinter.Tk()

path_of_directory = "D:\\Project_Symphogear"

width = root.winfo_screenwidth()
height = root.winfo_screenheight()

cover_width = 300
cover_height = 300

place_for_text_height = 50

# characters constants

attack = 50
HP = 5000



# playlists constants
# format = [title, name of file with song, is used, name of file with cover]

hibiki_songs = [
                ["Gekishou Gungnir", "gekishou_gungnir.oga", False, "gekishou_gungnir"],
                ["Watashi to Iu Oto Hibiki Sono Saki ni", "watashi.oga", False, "gekishou_gungnir"],
                ["Seigi wo Shinjite, Nigirishimete", "seigi.oga", False, "rainbow"],
                ["Rainbow flower", "rainbow_flower.ogg", False, "rainbow"],
                ["Genkai Toppa G-beat", "g_beat.oga", False, "miracle"],
                ["Genkai Toppa G-beat (IGNITED)", "g_beat_ignited.oga", False, "miracle"],
                ["Little Miracle -Grip it tight-", "little_miracle.oga", False, "miracle"],
                ["Makenai Ai ga Koko ni Aru", "makenai.oga", False, "hanasaku"],
                ["Hanasaku Yuki", "hanasaku_yuki.oga", False, "hanasaku"],
                ["Hanasaku Yuki (ver. Amalgam)", "hanasaku_yuki_amalgam.ogg", False, "hanasaku"],
                ["ALL LOVES BLAZING", "all_loves.ogg", False, "all_loves"],
                ["Kimi Dake ni", "kimi.ogg", False, "all_loves"],
                ["FIRST LOVE SONG", "first_love_song.oga", False, "first"],
                ["Radiant Force", "radiant_force.oga", False, "radiant"],
                ["Radiant Force (IGNITED)", "radiant_force_ignited.oga", False, "radiant"],
                ["Gekishou Infinity", "gekisho_infinity.oga", False, "radiant"],
                ["Gekishou Infinity (IGNITED)", "gekisho_infinity_ignited.oga", False, "radiant"],
                ["Hitsuai duo shout", "hitsuai_duo_shout.oga", False, "hitsuai"],
                ["Hajimari no babel", "hajimari_no_babel.oga", False, "hajimari"],
                ["Axia no kaze", "axia_no_kaze.oga", False, "axia"],
                ["Rikka Ryouran", "rikka.ogg", False, "rikka"],
                ["PERFECT SYMPHONY", "perfect_symphony.ogg", False, "perfect_symphony"],
                ["Xtreme Vibes", "xtreme_vibes.ogg", False, "perfect_symphony"],
                ["Ashita e no Fugel", "ashita.ogg", False, "ashita"],
                ["Koso Gungnir", "koso_gungnir.ogg", False, "xdu"]
]

tsubasa_songs = [
                ["Zettou Ame no Habakiri", "zettou.oga", False, "zettou"],
                ["FLIGHT FEATHERS", "flight.oga", False, "zettou"],
                ["Gekkou no Tsurugi", "gekko.oga", False, "gekko"],
                ["Koi no Okehazama", "koi.oga", False, "gekko"],
                ["Beyond the blade", "beyond_the_blade.oga", False, "beyond"],
                ["Beyond the blade (IGNITED)", "beyond_the_blade_ignited.oga", False, "beyond"],
                ["Sora e...", "sora.oga", False, "beyond"],
                ["Gekka Bijin", "gekka.oga", False, "gekka"],
                ["Luminous Gate", "luminous.oga", False, "gekka"],
                ["Defender'Z Brand!", "defender.ogg", False, "defender"],
                ["Kaze no Anata ni", "kaze_no.ogg", False, "defender"],
                ["BAYONET CHARGE", "bayonet.oga", False, "bayonet"],
                ["FIRST LOVE SONG", "first_love_song.oga", False, "first"],
                ["Radiant Force", "radiant_force.oga", False, "radiant"],
                ["Radiant Force (IGNITED)", "radiant_force_ignited.oga", False, "radiant"],
                ["Gekishou Infinity", "gekisho_infinity.oga", False, "radiant"],
                ["Gekishou Infinity (IGNITED)", "gekisho_infinity_ignited.oga", False, "radiant"],
                ["Fugetsu no shisso", "fugetsu_no_shisso.oga", False, "fugetsu"],
                ["Hajimari no babel", "hajimari_no_babel.oga", False, "hajimari"],
                ["Axia no kaze", "axia_no_kaze.oga", False, "axia"],
                ["Rikka Ryouran", "rikka.ogg", False, "rikka"],
                ["PERFECT SYMPHONY", "perfect_symphony.ogg", False, "perfect_symphony"],
                ["Xtreme Vibes", "xtreme_vibes.ogg", False, "perfect_symphony"],
                ["Ashita e no Fugel", "ashita.ogg", False, "ashita"],
                ["Sakimori no Uta", "sakimori_no_uta.ogg", False, "xdu"]
]

chris_songs = [
                ["Makyuu Ichaival", "makyu.oga", False, "tsunaida"],
                ["Tsunaida Te Dake ga Tsumugu Mono", "tsunaida_te_dake_ga_tsumugu_mono.oga", False, "tsunaida"],
                ["Bye-Bye Lullaby", "bye_bye.oga", False, "bye_bye"],
                ["Kyoushitsu Monochrome", "kyoshitsu.oga", False, "bye_bye"],
                ["TRUST HEART", "trust.oga", False, "trust"],
                ["TRUST HEART (IGNITED)", "trust_ignite.oga", False, "trust"],
                ["Houkago Key Holder", "houkago.oga", False, "trust"],
                ["Gun bullet XXX", "gun_bullet_xxx.oga", False, "gun"],
                ["Todoke Happy Uta Zukin!", "todoke.oga", False, "gun"],
                ["Take this! All loaded", "take_this.ogg", False, "take_this"],
                ["Ashita no Atashi", "ashita_no_atashi.ogg", False, "take_this"],
                ["BAYONET CHANGE", "bayonet.oga", False, "bayonet"],
                ["FIRST LOVE SONG", "first_love_song.oga", False, "first"],
                ["Radiant Force", "radiant_force.oga", False, "radiant"],
                ["Radiant Force (IGNITED)", "radiant_force_ignited.oga", False, "radiant"],
                ["Gekishou Infinity", "gekisho_infinity.oga", False, "radiant"],
                ["Gekishou Infinity (IGNITED)", "gekisho_infinity_ignited.oga", False, "radiant"],
                ["Change the future", "change_the_future.oga", False, "change"],
                ["Hajimari no babel", "hajimari_no_babel.oga", False, "hajimari"],
                ["Axia no kaze", "axia_no_kaze.oga", False, "axia"],
                ["Rikka Ryouran", "rikka.ogg", False, "rikka"],
                ["PERFECT SYMPHONY", "perfect_symphony.ogg", False, "perfect_symphony"],
                ["Xtreme Vibes", "xtreme_vibes.ogg", False, "perfect_symphony"],
                ["Ashita e no Fugel", "ashita.ogg", False, "ashita"]
]

maria_songs = [
                ["Ginwan Airgetlam", "ginwan.oga", False, "ginwan"],
                ["Ginwan Airgetlam (IGNITED)", "ginwan_ignited.oga", False, "ginwan"],
                ["Junpaku Innocent", "junpaku.oga", False, "ginwan"],
                ["Stand up! Ready!", "stand_up.oga", False, "stand_up"],
                ["Shirogane no Honou -keep the faith-", "keep_the_faith.ogg", False, "keep_the_faith"],
                ["Kono Ima wo Ikiru Hikari", "kono.ogg", False, "keep_the_faith"],
                ["Arigatou wo utai Nagara", "arigato.oga", False, "arigatou"],
                ["Senritsu Sorority", "senritsu.oga", False, "arigatou"],
                ["Senritsu Sorority (IGNITED)", "senritsu_ignited.oga", False, "arigatou"],
                ["Change the future", "change_the_future.oga", False, "change"],
                ["Hajimari no babel", "hajimari_no_babel.oga", False, "hajimari"],
                ["Axia no kaze", "axia_no_kaze.oga", False, "axia"],
                ["Rikka Ryouran", "rikka.ogg", False, "rikka"],
                ["PERFECT SYMPHONY", "perfect_symphony.ogg", False, "perfect_symphony"],
                ["Xtreme Vibes", "xtreme_vibes.ogg", False, "perfect_symphony"],
                ["Ashita e no Fugel", "ashita.ogg", False, "ashita"],
                ["Koso Gungnir", "koso_gungnir.ogg", False, "xdu"]
]

shirabe_songs = [
                ["Okyo Shul Shagana", "okyo.oga", False, "okyo"],
                ["PRACTICE MODE", "practice.oga", False, "okyo"],
                ["Genocide Saw Heaven", "genocide_saw_heaven.oga", False, "genocide_saw_heaven"],
                ["SENSE OF DISTANCE", "sense.oga", False, "genocide_saw_heaven"],
                ["Melodious Moonlight", "moonlight.oga", False, "moonlight"],
                ["Draft folder", "draft.oga", False, "moonlight"],
                ["Mijuku Shoujo Buttagiri!", "buttagirl.ogg", False, "buttagiri"],
                ["Kimi ga Nakanai Sekai ni", "kimi_ga.ogg", False, "buttagiri"],
                ["Edge Works of Goddess ZABABA", "edge_works.oga",False, "gizagizagirari"],
                ["Just Loving X-Edge", "just_loving.oga", False, "gizagizagirari"],
                ["Just Loving X-Edge (IGNITED)", "just_loving_ignited.oga", False, "gizagizagirari"],
                ["Gizagizagirari - Full Throttle", "gizagizagirari.oga", False, "gizagizagirari"],
                ["Cutting Edgex2 Ready go!", "cutting_edge_2x_ready_go.ogg", False, "sforzando_no_zankyou"],
                ["Arigatou wo utai Nagara", "arigato.oga", False, "arigatou"],
                ["Senritsu Sorority", "senritsu.oga", False, "arigatou"],
                ["Senritsu Sorority (IGNITED)", "senritsu_ignited.oga", False, "arigatou"],
                ["Fugetsu no shisso", "fugetsu_no_shisso.oga", False, "fugetsu"],
                ["Hajimari no babel", "hajimari_no_babel.oga", False, "hajimari"],
                ["Axia no kaze", "axia_no_kaze.oga", False, "axia"],
                ["Rikka Ryouran", "rikka.ogg", False, "rikka"],
                ["PERFECT SYMPHONY", "perfect_symphony.ogg", False, "perfect_symphony"],
                ["Xtreme Vibes", "xtreme_vibes.ogg", False, "perfect_symphony"],
                ["Ashita e no Fugel", "ashita.ogg", False, "ashita"]
]

kirika_songs = [
                ["Gokuren Igalima", "gokuren_igalima.oga", False, "gokuren"],
                ["Tegami", "tegami.oga", False, "gokuren"],
                ["Overkill Scythe Hell", "overkill_scythe_hell.oga", False, "overkill_scythe_hell"],
                ["Okitegami", "okitegami.oga", False, "overkill_scythe_hell"],
                ["Dangerous Sunshine", "dangerous_sunshine.oga", False, "dangerous"],
                ["Happy Smile Vacation", "happy.oga", False, "dangerous"],
                ["Mikansei Ai Mapputatsu!", "mapputatsu.ogg", False, "mapputatsu"],
                ["Happy Birthday no Uta", "happy_b-day.ogg", False, "mapputatsu"],
                ["Edge Works of Goddess ZABABA", "edge_works.oga", False, "gizagizagirari"],
                ["Just Loving X-Edge", "just_loving.oga", False, "gizagizagirari"],
                ["Just Loving X-Edge (IGNITED)", "just_loving_ignited.oga", False, "gizagizagirari"],
                ["Gizagizagirari - Full Throttle", "gizagizagirari.oga", False, "gizagizagirari"],
                ["Cutting Edgex2 Ready go!", "cutting_edge_2x_ready_go.ogg", False, "sforzando_no_zankyou"],
                ["Arigatou wo utai Nagara", "arigato.oga", False, "arigatou"],
                ["Senritsu Sorority", "senritsu.oga", False, "arigatou"],
                ["Senritsu Sorority (IGNITED)", "senritsu_ignited.oga", False, "arigatou"],
                ["Hitsuai duo shout", "hitsuai_duo_shout.oga", False, "hitsuai"],
                ["Hajimari no babel", "hajimari_no_babel.oga", False, "hajimari"],
                ["Axia no kaze", "axia_no_kaze.oga", False, "axia"],
                ["Rikka Ryouran", "rikka.ogg", False, "rikka"],
                ["PERFECT SYMPHONY", "perfect_symphony.ogg", False, "perfect_symphony"],
                ["Xtreme Vibes", "xtreme_vibes.ogg", False, "perfect_symphony"],
                ["Ashita e no Fugel", "ashita.ogg", False, "ashita"]
]

miku_songs = [
                ["Waikyou Shenshoujing", "shenshoujing.oga", False, "shenshoujin"],
                ["Kaban no Kakushigoto", "kaban.oga", False, "shenshoujin"],
                ["Eiai Promise", "eiai.oga", False, "shenshoujin"],
                ["Hidamari memoria", "hidamari.oga", False, "shenshoujin"],
                ["FOR THE FUTURE", "for_the_future.ogg", False, "ashita"],
                ["Radiant Force", "radiant_force.oga", False, "radiant"],
                ["Radiant Force (IGNITED)", "radiant_force_ignited.oga", False, "radiant"],
                ["Gekishou Infinity", "gekisho_infinity.oga", False, "radiant"],
                ["Gekishou Infinity (IGNITED)", "gekisho_infinity_ignited.oga", False, "radiant"],
                ["Hajimari no babel", "hajimari_no_babel.oga", False, "hajimari"],
                ["Axia no kaze", "axia_no_kaze.oga", False, "axia"],
                ["Rikka Ryouran", "rikka.ogg", False, "rikka"],
                ["PERFECT SYMPHONY", "perfect_symphony.ogg", False, "perfect_symphony"],
                ["Xtreme Vibes", "xtreme_vibes.ogg", False, "perfect_symphony"],
                ["Ashita e no Fugel", "ashita.ogg", False, "ashita"]
]

all_songs = [
            ["SYNCHROGAZER", "synchrogazer.ogg", False, "synchrogazer"],
                ["Vitalization", "vitalization.oga", False, "vitalization"],
                ["Glorious Brake", "glorious.oga", False, "glorious"],
                ["Exterminate", "exterminate.mp3", False, "glorious"],
                ["TESTAMENT", "testament.oga", False, "testament"],
                ["METANOIA", "metanoia.ogg", False, "metanoia"],
                ["FINAL COMMANDER", "final.ogg", False, "final"],
            ["Gekishou Gungnir", "gekishou_gungnir.oga", False, "gekishou_gungnir"],
                ["Watashi to Iu Oto Hibiki Sono Saki ni", "watashi.oga", False, "gekishou_gungnir"],
                ["Seigi wo Shinjite, Nigirishimete", "seigi.oga", False, "rainbow"],
                ["Rainbow flower", "rainbow_flower.ogg", False, "rainbow"],
                ["Genkai Toppa G-beat", "g_beat.oga", False, "miracle"],
                ["Genkai Toppa G-beat (IGNITED)", "g_beat_ignited.oga", False, "miracle"],
                ["Little Miracle -Grip it tight-", "little_miracle.oga", False, "miracle"],
                ["Makenai Ai ga Koko ni Aru", "makenai.oga", False, "hanasaku"],
                ["Hanasaku Yuki", "hanasaku_yuki.oga", False, "hanasaku"],
                ["Hanasaku Yuki (ver. Amalgam)", "hanasaku_yuki_amalgam.ogg", False, "hanasaku"],
                ["ALL LOVES BLAZING", "all_loves.ogg", False, "all_loves"],
                ["Kimi Dake ni", "kimi.ogg", False, "all_loves"],
            ["Zettou Ame no Habakiri", "zettou.oga", False, "zettou"],
                ["FLIGHT FEATHERS", "flight.oga", False, "zettou"],
                ["Gekkou no Tsurugi", "gekko.oga", False, "gekko"],
                ["Koi no Okehazama", "koi.oga", False, "gekko"],
                ["Beyond the blade", "beyond_the_blade.oga", False, "beyond"],
                ["Beyond the blade (IGNITED)", "beyond_the_blade_ignited.oga", False, "beyond"],
                ["Sora e...", "sora.oga", False, "beyond"],
                ["Gekka Bijin", "gekka.oga", False, "gekka"],
                ["Luminous Gate", "luminous.oga", False, "gekka"],
                ["Defender'Z Brand!", "defender.ogg", False, "defender"],
                ["Kaze no Anata ni", "kaze_no.ogg", False, "defender"],
            ["Makyuu Ichaival", "makyu.oga", False, "tsunaida"],
                ["Tsunaida Te Dake ga Tsumugu Mono", "tsunaida_te_dake_ga_tsumugu_mono.oga", False, "tsunaida"],
                ["Bye-Bye Lullaby", "bye_bye.oga", False, "bye_bye"],
                ["Kyoushitsu Monochrome", "kyoshitsu.oga", False, "bye_bye"],
                ["TRUST HEART", "trust.oga", False, "trust"],
                ["TRUST HEART (IGNITED)", "trust_ignite.oga", False, "trust"],
                ["Houkago Key Holder", "houkago.oga", False, "trust"],
                ["Gun bullet XXX", "gun_bullet_xxx.oga", False, "gun"],
                ["Todoke Happy Uta Zukin!", "todoke.oga", False, "gun"],
                ["Take this! All loaded", "take_this.ogg", False, "take_this"],
                ["Ashita no Atashi", "ashita_no_atashi.ogg", False, "take_this"],
            ["Ginwan Airgetlam", "ginwan.oga", False, "ginwan"],
                ["Ginwan Airgetlam (IGNITED)", "ginwan_ignited.oga", False, "ginwan"],
                ["Junpaku Innocent", "junpaku.oga", False, "ginwan"],
                ["Stand up! Ready!", "stand_up.oga", False, "stand_up"],
                ["Shirogane no Honou -keep the faith-", "keep_the_faith.ogg", False, "keep_the_faith"],
                ["Kono Ima wo Ikiru Hikari", "kono.ogg", False, "keep_the_faith"],
            ["Okyo Shul Shagana", "okyo.oga", False, "okyo"],
                ["PRACTICE MODE", "practice.oga", False, "okyo"],
                ["Genocide Saw Heaven", "genocide_saw_heaven.oga", False, "genocide_saw_heaven"],
                ["SENSE OF DISTANCE", "sense.oga", False, "genocide_saw_heaven"],
                ["Melodious Moonlight", "moonlight.oga", False, "moonlight"],
                ["Draft folder", "draft.oga", False, "moonlight"],
                ["Mijuku Shoujo Buttagiri!", "buttagirl.ogg", False, "buttagiri"],
                ["Kimi ga Nakanai Sekai ni", "kimi_ga.ogg", False, "buttagiri"],
            ["Gokuren Igalima", "gokuren_igalima.oga", False, "gokuren"],
                ["Tegami", "tegami.oga", False, "gokuren"],
                ["Overkill Scythe Hell", "overkill_scythe_hell.oga", False, "overkill_scythe_hell"],
                ["Okitegami", "okitegami.oga", False, "overkill_scythe_hell"],
                ["Dangerous Sunshine", "dangerous_sunshine.oga", False, "dangerous"],
                ["Happy Smile Vacation", "happy.oga", False, "dangerous"],
                ["Mikansei Ai Mapputatsu!", "mapputatsu.ogg", False, "mapputatsu"],
                ["Happy Birthday no Uta", "happy_b-day.ogg", False, "mapputatsu"],
            ["Edge Works of Goddess ZABABA", "edge_works.oga", False, "gizagizagirari"],
                ["Just Loving X-Edge", "just_loving.oga", False, "gizagizagirari"],
                ["Just Loving X-Edge (IGNITED)", "just_loving_ignited.oga", False, "gizagizagirari"],
                ["Gizagizagirari - Full Throttle", "gizagizagirari.oga", False, "gizagizagirari"],
                ["Cutting Edgex2 Ready go!", "cutting_edge_2x_ready_go.ogg", False, "sforzando_no_zankyou"],
            ["Waikyou Shenshoujing", "shenshoujing.oga", False, "shenshoujin"],
                ["Kaban no Kakushigoto", "kaban.oga", False, "shenshoujin"],
                ["Eiai Promise", "eiai.oga", False, "shenshoujin"],
                ["Hidamari memoria", "hidamari.oga", False, "shenshoujin"],
                ["FOR THE FUTURE", "for_the_future.ogg", False, "ashita"],
            ["FIRST LOVE SONG", "first_love_song.oga", False, "first"],
                ["Radiant Force", "radiant_force.oga", False, "radiant"],
                ["Radiant Force (IGNITED)", "radiant_force_ignited.oga", False, "radiant"],
                ["Gekishou Infinity", "gekisho_infinity.oga", False, "radiant"],
                ["Gekishou Infinity (IGNITED)", "gekisho_infinity_ignited.oga", False, "radiant"],
            ["Arigatou wo utai Nagara", "arigato.oga", False, "arigatou"],
                ["Senritsu Sorority", "senritsu.oga", False, "arigatou"],
                ["Senritsu Sorority (IGNITED)", "senritsu_ignited.oga", False, "arigatou"],
            ["Change the future", "change_the_future.oga", False, "change"],
            ["Fugetsu no shisso", "fugetsu_no_shisso.oga", False, "fugetsu"],
            ["Hitsuai duo shout", "hitsuai_duo_shout.oga", False, "hitsuai"],
            ["Hajimari no babel", "hajimari_no_babel.oga", False, "hajimari"],
                ["Axia no kaze", "axia_no_kaze.oga", False, "axia"],
                ["Rikka Ryouran", "rikka.ogg", False, "rikka"],
                ["PERFECT SYMPHONY", "perfect_symphony.ogg", False, "perfect_symphony"],
                ["Xtreme Vibes", "xtreme_vibes.ogg", False, "perfect_symphony"],
                ["Ashita e no Fugel", "ashita.ogg", False, "ashita"],
            ["Shitou -Ewigkeit-", "shitou.oga", False, "shitou"],
            ["Senkin Dur Da Bla", "senkin_dur_da_bla.oga", False, "senkin_dur_da_bla"],
            ["Tommorow", "tommorow.oga", False, "senkin_dur_da_bla"],
            ["Green Green", "green_green.oga", False, "green_green"],
            ["Sforzando no Zankyou", "sforzando_no_zankyou.ogg", False, "sforzando_no_zankyou"],
            ["Gyakkou no Flugel", "gaykkou.oga", False, "orbital_beat"],
            ["Meteor Light", "meteor_light.oga", False, "meteor_light"],
            ["Next Destination", "next_destination.oga", False, "next_destination"],
            ["Rebirth-day", "rebirth.oga", False, "rebirth"],
            ["Futurism", "futurism.oga", False, "futurism"],
            ["Lasting Song", "lasting.ogg", False, "lasting"],
            ["Nijiiro no Flugel", "nijiiro.oga", False, "axia"],
            ["ORBITAL BEAT", "orbital_beat.oga", False, "orbital_beat"],
            ["ORBITAL BEAT (Ver. ZABABA)", "orbital_beat_zababa.oga", False, "gizagizagirari"],
            ["Fushichu no Flamme", "flamme.oga", False, "flamme"],
            ["Seiten Galaxy Cross", "galaxy_cross.oga", False, "galaxy_cross"],
            ["Ressou Gungnir", "resso.oga", False, "resso"],
            ["Dark Oblivion", "dark.oga", False, "resso"],
            ["Koso Gungnir", "koso_gungnir.ogg", False, "xdu"],
            ["Sakimori no Uta", "sakimori_no_uta.ogg", False, "xdu"],
            ["More than friends, less than heroes", "more_than_friends_less_than_heroes.mp3", False, "xdu"]
]

def write_to_csv():
    with open('songs.csv', 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['title', 'name of file with song', 'name of file with cover'])
        for line in all_songs:
            writer.writerow([line[i] for i in [0, 1, -1]])